fragment HomeParts on Home {
  __typename
  title
  name
  role
  affiliation
  email1
  email2
  phone
  orcid
  googleScholar
  logo
  profilePhoto
  cvFile
  body
  recentNews {
    __typename
    item
  }
  specialization {
    __typename
    item
  }
  education {
    __typename
    item
  }
  experience {
    __typename
    item
  }
  administrativeExperience {
    __typename
    item
  }
  publications {
    __typename
    item
  }
  patents {
    __typename
    item
  }
  supervision {
    __typename
    item
  }
}

fragment PagesParts on Pages {
  __typename
  title
  pdfFile
  body
}

fragment EcontentParts on Econtent {
  __typename
  title
  topics {
    __typename
    topicName
    notes
    pdf
    link
  }
  body
}
