//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  import type { TinaMarkdownContent } from 'tinacms/dist/rich-text';
/** Internal type. DO NOT USE DIRECTLY. */
type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
/** Internal type. DO NOT USE DIRECTLY. */
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
  /** A rich-text document, renderable by TinaMarkdown */
  RichText: { input: TinaMarkdownContent; output: TinaMarkdownContent; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  home: Home;
  homeConnection: HomeConnection;
  pages: Pages;
  pagesConnection: PagesConnection;
  econtent: Econtent;
  econtentConnection: EcontentConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHomeArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHomeConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomeFilter>;
};


export type QueryPagesArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPagesConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PagesFilter>;
};


export type QueryEcontentArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryEcontentConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<EcontentFilter>;
};

export type DocumentFilter = {
  home?: InputMaybe<HomeFilter>;
  pages?: InputMaybe<PagesFilter>;
  econtent?: InputMaybe<EcontentFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Home | Pages | Econtent | Folder;

export type HomeRecentNews = {
  __typename?: 'HomeRecentNews';
  item?: Maybe<Scalars['String']['output']>;
};

export type HomeSpecialization = {
  __typename?: 'HomeSpecialization';
  item?: Maybe<Scalars['String']['output']>;
};

export type HomeEducation = {
  __typename?: 'HomeEducation';
  item?: Maybe<Scalars['String']['output']>;
};

export type HomeExperience = {
  __typename?: 'HomeExperience';
  item?: Maybe<Scalars['String']['output']>;
};

export type HomeAdministrativeExperience = {
  __typename?: 'HomeAdministrativeExperience';
  item?: Maybe<Scalars['String']['output']>;
};

export type HomePublications = {
  __typename?: 'HomePublications';
  item?: Maybe<Scalars['String']['output']>;
};

export type HomePatents = {
  __typename?: 'HomePatents';
  item?: Maybe<Scalars['String']['output']>;
};

export type HomeSupervision = {
  __typename?: 'HomeSupervision';
  item?: Maybe<Scalars['String']['output']>;
};

export type Home = Node & Document & {
  __typename?: 'Home';
  title: Scalars['String']['output'];
  name?: Maybe<Scalars['String']['output']>;
  role?: Maybe<Scalars['String']['output']>;
  affiliation?: Maybe<Scalars['String']['output']>;
  email1?: Maybe<Scalars['String']['output']>;
  email2?: Maybe<Scalars['String']['output']>;
  phone?: Maybe<Scalars['String']['output']>;
  orcid?: Maybe<Scalars['String']['output']>;
  googleScholar?: Maybe<Scalars['String']['output']>;
  logo?: Maybe<Scalars['String']['output']>;
  profilePhoto?: Maybe<Scalars['String']['output']>;
  cvFile?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['RichText']['output']>;
  recentNews?: Maybe<Array<Maybe<HomeRecentNews>>>;
  specialization?: Maybe<Array<Maybe<HomeSpecialization>>>;
  education?: Maybe<Array<Maybe<HomeEducation>>>;
  experience?: Maybe<Array<Maybe<HomeExperience>>>;
  administrativeExperience?: Maybe<Array<Maybe<HomeAdministrativeExperience>>>;
  publications?: Maybe<Array<Maybe<HomePublications>>>;
  patents?: Maybe<Array<Maybe<HomePatents>>>;
  supervision?: Maybe<Array<Maybe<HomeSupervision>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type RichTextFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type HomeRecentNewsFilter = {
  item?: InputMaybe<StringFilter>;
};

export type HomeSpecializationFilter = {
  item?: InputMaybe<StringFilter>;
};

export type HomeEducationFilter = {
  item?: InputMaybe<StringFilter>;
};

export type HomeExperienceFilter = {
  item?: InputMaybe<StringFilter>;
};

export type HomeAdministrativeExperienceFilter = {
  item?: InputMaybe<StringFilter>;
};

export type HomePublicationsFilter = {
  item?: InputMaybe<StringFilter>;
};

export type HomePatentsFilter = {
  item?: InputMaybe<StringFilter>;
};

export type HomeSupervisionFilter = {
  item?: InputMaybe<StringFilter>;
};

export type HomeFilter = {
  title?: InputMaybe<StringFilter>;
  name?: InputMaybe<StringFilter>;
  role?: InputMaybe<StringFilter>;
  affiliation?: InputMaybe<StringFilter>;
  email1?: InputMaybe<StringFilter>;
  email2?: InputMaybe<StringFilter>;
  phone?: InputMaybe<StringFilter>;
  orcid?: InputMaybe<StringFilter>;
  googleScholar?: InputMaybe<StringFilter>;
  logo?: InputMaybe<ImageFilter>;
  profilePhoto?: InputMaybe<ImageFilter>;
  cvFile?: InputMaybe<ImageFilter>;
  body?: InputMaybe<RichTextFilter>;
  recentNews?: InputMaybe<HomeRecentNewsFilter>;
  specialization?: InputMaybe<HomeSpecializationFilter>;
  education?: InputMaybe<HomeEducationFilter>;
  experience?: InputMaybe<HomeExperienceFilter>;
  administrativeExperience?: InputMaybe<HomeAdministrativeExperienceFilter>;
  publications?: InputMaybe<HomePublicationsFilter>;
  patents?: InputMaybe<HomePatentsFilter>;
  supervision?: InputMaybe<HomeSupervisionFilter>;
};

export type HomeConnectionEdges = {
  __typename?: 'HomeConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Home>;
};

export type HomeConnection = Connection & {
  __typename?: 'HomeConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<HomeConnectionEdges>>>;
};

export type Pages = Node & Document & {
  __typename?: 'Pages';
  title: Scalars['String']['output'];
  pdfFile?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['RichText']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type PagesFilter = {
  title?: InputMaybe<StringFilter>;
  pdfFile?: InputMaybe<ImageFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type PagesConnectionEdges = {
  __typename?: 'PagesConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Pages>;
};

export type PagesConnection = Connection & {
  __typename?: 'PagesConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PagesConnectionEdges>>>;
};

export type EcontentLinks = {
  __typename?: 'EcontentLinks';
  label?: Maybe<Scalars['String']['output']>;
  url?: Maybe<Scalars['String']['output']>;
};

export type Econtent = Node & Document & {
  __typename?: 'Econtent';
  title: Scalars['String']['output'];
  links?: Maybe<Array<Maybe<EcontentLinks>>>;
  body?: Maybe<Scalars['RichText']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type EcontentLinksFilter = {
  label?: InputMaybe<StringFilter>;
  url?: InputMaybe<StringFilter>;
};

export type EcontentFilter = {
  title?: InputMaybe<StringFilter>;
  links?: InputMaybe<EcontentLinksFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type EcontentConnectionEdges = {
  __typename?: 'EcontentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Econtent>;
};

export type EcontentConnection = Connection & {
  __typename?: 'EcontentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<EcontentConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateHome: Home;
  createHome: Home;
  updatePages: Pages;
  createPages: Pages;
  updateEcontent: Econtent;
  createEcontent: Econtent;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateHomeArgs = {
  relativePath: Scalars['String']['input'];
  params: HomeMutation;
};


export type MutationCreateHomeArgs = {
  relativePath: Scalars['String']['input'];
  params: HomeMutation;
};


export type MutationUpdatePagesArgs = {
  relativePath: Scalars['String']['input'];
  params: PagesMutation;
};


export type MutationCreatePagesArgs = {
  relativePath: Scalars['String']['input'];
  params: PagesMutation;
};


export type MutationUpdateEcontentArgs = {
  relativePath: Scalars['String']['input'];
  params: EcontentMutation;
};


export type MutationCreateEcontentArgs = {
  relativePath: Scalars['String']['input'];
  params: EcontentMutation;
};

export type DocumentUpdateMutation = {
  home?: InputMaybe<HomeMutation>;
  pages?: InputMaybe<PagesMutation>;
  econtent?: InputMaybe<EcontentMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  home?: InputMaybe<HomeMutation>;
  pages?: InputMaybe<PagesMutation>;
  econtent?: InputMaybe<EcontentMutation>;
};

export type HomeRecentNewsMutation = {
  item?: InputMaybe<Scalars['String']['input']>;
};

export type HomeSpecializationMutation = {
  item?: InputMaybe<Scalars['String']['input']>;
};

export type HomeEducationMutation = {
  item?: InputMaybe<Scalars['String']['input']>;
};

export type HomeExperienceMutation = {
  item?: InputMaybe<Scalars['String']['input']>;
};

export type HomeAdministrativeExperienceMutation = {
  item?: InputMaybe<Scalars['String']['input']>;
};

export type HomePublicationsMutation = {
  item?: InputMaybe<Scalars['String']['input']>;
};

export type HomePatentsMutation = {
  item?: InputMaybe<Scalars['String']['input']>;
};

export type HomeSupervisionMutation = {
  item?: InputMaybe<Scalars['String']['input']>;
};

export type HomeMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  name?: InputMaybe<Scalars['String']['input']>;
  role?: InputMaybe<Scalars['String']['input']>;
  affiliation?: InputMaybe<Scalars['String']['input']>;
  email1?: InputMaybe<Scalars['String']['input']>;
  email2?: InputMaybe<Scalars['String']['input']>;
  phone?: InputMaybe<Scalars['String']['input']>;
  orcid?: InputMaybe<Scalars['String']['input']>;
  googleScholar?: InputMaybe<Scalars['String']['input']>;
  logo?: InputMaybe<Scalars['String']['input']>;
  profilePhoto?: InputMaybe<Scalars['String']['input']>;
  cvFile?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['RichText']['input']>;
  recentNews?: InputMaybe<Array<InputMaybe<HomeRecentNewsMutation>>>;
  specialization?: InputMaybe<Array<InputMaybe<HomeSpecializationMutation>>>;
  education?: InputMaybe<Array<InputMaybe<HomeEducationMutation>>>;
  experience?: InputMaybe<Array<InputMaybe<HomeExperienceMutation>>>;
  administrativeExperience?: InputMaybe<Array<InputMaybe<HomeAdministrativeExperienceMutation>>>;
  publications?: InputMaybe<Array<InputMaybe<HomePublicationsMutation>>>;
  patents?: InputMaybe<Array<InputMaybe<HomePatentsMutation>>>;
  supervision?: InputMaybe<Array<InputMaybe<HomeSupervisionMutation>>>;
};

export type PagesMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  pdfFile?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['RichText']['input']>;
};

export type EcontentLinksMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  url?: InputMaybe<Scalars['String']['input']>;
};

export type EcontentMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  links?: InputMaybe<Array<InputMaybe<EcontentLinksMutation>>>;
  body?: InputMaybe<Scalars['RichText']['input']>;
};

export type StringFilter = {
  startsWith?: string | null | undefined;
  eq?: string | null | undefined;
  exists?: boolean | null | undefined;
  in?: Array<string | null | undefined> | null | undefined;
};

export type ImageFilter = {
  startsWith?: string | null | undefined;
  eq?: string | null | undefined;
  exists?: boolean | null | undefined;
  in?: Array<string | null | undefined> | null | undefined;
};

export type RichTextFilter = {
  startsWith?: string | null | undefined;
  eq?: string | null | undefined;
  exists?: boolean | null | undefined;
};

export type HomeRecentNewsFilter = {
  item?: StringFilter | null | undefined;
};

export type HomeSpecializationFilter = {
  item?: StringFilter | null | undefined;
};

export type HomeEducationFilter = {
  item?: StringFilter | null | undefined;
};

export type HomeExperienceFilter = {
  item?: StringFilter | null | undefined;
};

export type HomeAdministrativeExperienceFilter = {
  item?: StringFilter | null | undefined;
};

export type HomePublicationsFilter = {
  item?: StringFilter | null | undefined;
};

export type HomePatentsFilter = {
  item?: StringFilter | null | undefined;
};

export type HomeSupervisionFilter = {
  item?: StringFilter | null | undefined;
};

export type HomeFilter = {
  title?: StringFilter | null | undefined;
  name?: StringFilter | null | undefined;
  role?: StringFilter | null | undefined;
  affiliation?: StringFilter | null | undefined;
  email1?: StringFilter | null | undefined;
  email2?: StringFilter | null | undefined;
  phone?: StringFilter | null | undefined;
  orcid?: StringFilter | null | undefined;
  googleScholar?: StringFilter | null | undefined;
  logo?: ImageFilter | null | undefined;
  profilePhoto?: ImageFilter | null | undefined;
  cvFile?: ImageFilter | null | undefined;
  body?: RichTextFilter | null | undefined;
  recentNews?: HomeRecentNewsFilter | null | undefined;
  specialization?: HomeSpecializationFilter | null | undefined;
  education?: HomeEducationFilter | null | undefined;
  experience?: HomeExperienceFilter | null | undefined;
  administrativeExperience?: HomeAdministrativeExperienceFilter | null | undefined;
  publications?: HomePublicationsFilter | null | undefined;
  patents?: HomePatentsFilter | null | undefined;
  supervision?: HomeSupervisionFilter | null | undefined;
};

export type PagesFilter = {
  title?: StringFilter | null | undefined;
  pdfFile?: ImageFilter | null | undefined;
  body?: RichTextFilter | null | undefined;
};

export type EcontentLinksFilter = {
  label?: StringFilter | null | undefined;
  url?: StringFilter | null | undefined;
};

export type EcontentFilter = {
  title?: StringFilter | null | undefined;
  links?: EcontentLinksFilter | null | undefined;
  body?: RichTextFilter | null | undefined;
};

export type HomePartsFragment = { __typename: 'Home', title: string, name: string | null, role: string | null, affiliation: string | null, email1: string | null, email2: string | null, phone: string | null, orcid: string | null, googleScholar: string | null, logo: string | null, profilePhoto: string | null, cvFile: string | null, body: TinaMarkdownContent | null, recentNews: Array<{ __typename: 'HomeRecentNews', item: string | null } | null> | null, specialization: Array<{ __typename: 'HomeSpecialization', item: string | null } | null> | null, education: Array<{ __typename: 'HomeEducation', item: string | null } | null> | null, experience: Array<{ __typename: 'HomeExperience', item: string | null } | null> | null, administrativeExperience: Array<{ __typename: 'HomeAdministrativeExperience', item: string | null } | null> | null, publications: Array<{ __typename: 'HomePublications', item: string | null } | null> | null, patents: Array<{ __typename: 'HomePatents', item: string | null } | null> | null, supervision: Array<{ __typename: 'HomeSupervision', item: string | null } | null> | null };

export type PagesPartsFragment = { __typename: 'Pages', title: string, pdfFile: string | null, body: TinaMarkdownContent | null };

export type EcontentPartsFragment = { __typename: 'Econtent', title: string, body: TinaMarkdownContent | null, links: Array<{ __typename: 'EcontentLinks', label: string | null, url: string | null } | null> | null };

export type HomeQueryVariables = Exact<{
  relativePath: string;
}>;


export type HomeQuery = { home: { __typename: 'Home', id: string, title: string, name: string | null, role: string | null, affiliation: string | null, email1: string | null, email2: string | null, phone: string | null, orcid: string | null, googleScholar: string | null, logo: string | null, profilePhoto: string | null, cvFile: string | null, body: TinaMarkdownContent | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, recentNews: Array<{ __typename: 'HomeRecentNews', item: string | null } | null> | null, specialization: Array<{ __typename: 'HomeSpecialization', item: string | null } | null> | null, education: Array<{ __typename: 'HomeEducation', item: string | null } | null> | null, experience: Array<{ __typename: 'HomeExperience', item: string | null } | null> | null, administrativeExperience: Array<{ __typename: 'HomeAdministrativeExperience', item: string | null } | null> | null, publications: Array<{ __typename: 'HomePublications', item: string | null } | null> | null, patents: Array<{ __typename: 'HomePatents', item: string | null } | null> | null, supervision: Array<{ __typename: 'HomeSupervision', item: string | null } | null> | null } };

export type HomeConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: HomeFilter | null | undefined;
}>;


export type HomeConnectionQuery = { homeConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'Home', id: string, title: string, name: string | null, role: string | null, affiliation: string | null, email1: string | null, email2: string | null, phone: string | null, orcid: string | null, googleScholar: string | null, logo: string | null, profilePhoto: string | null, cvFile: string | null, body: TinaMarkdownContent | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, recentNews: Array<{ __typename: 'HomeRecentNews', item: string | null } | null> | null, specialization: Array<{ __typename: 'HomeSpecialization', item: string | null } | null> | null, education: Array<{ __typename: 'HomeEducation', item: string | null } | null> | null, experience: Array<{ __typename: 'HomeExperience', item: string | null } | null> | null, administrativeExperience: Array<{ __typename: 'HomeAdministrativeExperience', item: string | null } | null> | null, publications: Array<{ __typename: 'HomePublications', item: string | null } | null> | null, patents: Array<{ __typename: 'HomePatents', item: string | null } | null> | null, supervision: Array<{ __typename: 'HomeSupervision', item: string | null } | null> | null } | null } | null> | null } };

export type PagesQueryVariables = Exact<{
  relativePath: string;
}>;


export type PagesQuery = { pages: { __typename: 'Pages', id: string, title: string, pdfFile: string | null, body: TinaMarkdownContent | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type PagesConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: PagesFilter | null | undefined;
}>;


export type PagesConnectionQuery = { pagesConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'Pages', id: string, title: string, pdfFile: string | null, body: TinaMarkdownContent | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type EcontentQueryVariables = Exact<{
  relativePath: string;
}>;


export type EcontentQuery = { econtent: { __typename: 'Econtent', id: string, title: string, body: TinaMarkdownContent | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, links: Array<{ __typename: 'EcontentLinks', label: string | null, url: string | null } | null> | null } };

export type EcontentConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: EcontentFilter | null | undefined;
}>;


export type EcontentConnectionQuery = { econtentConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'Econtent', id: string, title: string, body: TinaMarkdownContent | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, links: Array<{ __typename: 'EcontentLinks', label: string | null, url: string | null } | null> | null } | null } | null> | null } };

export const HomePartsFragmentDoc = gql`
    fragment HomeParts on Home {
  __typename
  title
  name
  role
  affiliation
  email1
  email2
  phone
  orcid
  googleScholar
  logo
  profilePhoto
  cvFile
  body
  recentNews {
    __typename
    item
  }
  specialization {
    __typename
    item
  }
  education {
    __typename
    item
  }
  experience {
    __typename
    item
  }
  administrativeExperience {
    __typename
    item
  }
  publications {
    __typename
    item
  }
  patents {
    __typename
    item
  }
  supervision {
    __typename
    item
  }
}
    `;
export const PagesPartsFragmentDoc = gql`
    fragment PagesParts on Pages {
  __typename
  title
  pdfFile
  body
}
    `;
export const EcontentPartsFragmentDoc = gql`
    fragment EcontentParts on Econtent {
  __typename
  title
  links {
    __typename
    label
    url
  }
  body
}
    `;
export const HomeDocument = gql`
    query home($relativePath: String!) {
  home(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...HomeParts
  }
}
    ${HomePartsFragmentDoc}`;
export const HomeConnectionDocument = gql`
    query homeConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: HomeFilter) {
  homeConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...HomeParts
      }
    }
  }
}
    ${HomePartsFragmentDoc}`;
export const PagesDocument = gql`
    query pages($relativePath: String!) {
  pages(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PagesParts
  }
}
    ${PagesPartsFragmentDoc}`;
export const PagesConnectionDocument = gql`
    query pagesConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PagesFilter) {
  pagesConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PagesParts
      }
    }
  }
}
    ${PagesPartsFragmentDoc}`;
export const EcontentDocument = gql`
    query econtent($relativePath: String!) {
  econtent(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...EcontentParts
  }
}
    ${EcontentPartsFragmentDoc}`;
export const EcontentConnectionDocument = gql`
    query econtentConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: EcontentFilter) {
  econtentConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...EcontentParts
      }
    }
  }
}
    ${EcontentPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      home(variables: HomeQueryVariables, options?: C): Promise<{data: HomeQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeQueryVariables, query: string}> {
        return requester<{data: HomeQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeQueryVariables, query: string}, HomeQueryVariables>(HomeDocument, variables, options);
      },
    homeConnection(variables?: HomeConnectionQueryVariables, options?: C): Promise<{data: HomeConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeConnectionQueryVariables, query: string}> {
        return requester<{data: HomeConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeConnectionQueryVariables, query: string}, HomeConnectionQueryVariables>(HomeConnectionDocument, variables, options);
      },
    pages(variables: PagesQueryVariables, options?: C): Promise<{data: PagesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PagesQueryVariables, query: string}> {
        return requester<{data: PagesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PagesQueryVariables, query: string}, PagesQueryVariables>(PagesDocument, variables, options);
      },
    pagesConnection(variables?: PagesConnectionQueryVariables, options?: C): Promise<{data: PagesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PagesConnectionQueryVariables, query: string}> {
        return requester<{data: PagesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PagesConnectionQueryVariables, query: string}, PagesConnectionQueryVariables>(PagesConnectionDocument, variables, options);
      },
    econtent(variables: EcontentQueryVariables, options?: C): Promise<{data: EcontentQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EcontentQueryVariables, query: string}> {
        return requester<{data: EcontentQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EcontentQueryVariables, query: string}, EcontentQueryVariables>(EcontentDocument, variables, options);
      },
    econtentConnection(variables?: EcontentConnectionQueryVariables, options?: C): Promise<{data: EcontentConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EcontentConnectionQueryVariables, query: string}> {
        return requester<{data: EcontentConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EcontentConnectionQueryVariables, query: string}, EcontentConnectionQueryVariables>(EcontentConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

export type { Exact };

  